baseURL: "https://tech.gsa.gov/"
languageCode: "en-US"
title: "Tech at GSA"
canonifyURLs: true
buildFuture: true

params:
  description: "Design and development resources to build modern digital services at GSA"

markup:
  goldmark:
    renderer:
      unsafe: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

security:
  exec:
    allow: ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', '^babel$']

module:
  mounts:
    - source: "static"
      target: "static"
    - source: "node_modules/netlify-cms/dist"
      target: "static/assets/netlify-cms"
    - source: "node_modules/markdown-it/dist"
      target: "static/assets/markdown-it"
    - source: "node_modules/jquery/dist"
      target: "static/assets/jquery"
    - source: "node_modules/waypoints/lib"
      target: "static/assets/waypoints"
    - source: "node_modules/mousetrap/mousetrap.min.js"
      target: "static/assets/mousetrap/mousetrap.min.js"
    - source: "node_modules/@fortawesome/fontawesome-free"
      target: "static/assets/fontawesome-free"
    - source: "node_modules/lunr/lunr.min.js"
      target: "static/assets/lunr/lunr.min.js"
    - source: "node_modules/react/umd/react.production.min.js"
      target: "static/assets/react/react.production.min.js"
