backend:
  name: github
  repo: GSA/cto-website
  base_url: https://federalistapp.18f.gov
  auth_endpoint: external/auth/github
  preview_context: federalist/build
  branch: main

site_url: https://tech.gsa.gov/
logo_url: https://tech.gsa.gov/assets/img/gsa_logo.svg
publish_mode: editorial_workflow
media_folder: /assets/files

collections:

  - label: Tech Talk
    name: techtalk
    folder: _techtalks
    create: true
    summary: "{{date}} - {{title}}"
    slug: "{{fields.date}}-{{slug}}"
    media_folder: "/assets/files/techtalks"
    fields:
      - { label: "Title", name: title, widget: string }
      - { label: "Date", name: date, widget: datetime, format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false }
      - { label: "Time", name: time, widget: string, default: "1:00pm - 1:30pm ET" }
      - { label: "Location", name: location, widget: string }
      - { label: "Presenter", name: presenter, widget: string }
      - { label: "Slides", name: slides, required: false, widget: file }
      - { label: "Description", name: body, widget: markdown }

  - label: Team
    name: team
    folder: _team
    create: true
    summary: "{{firstname}} {{lastname}}"
    media_folder: "/assets/files/team"
    fields:
      - { label: "First Name", name: firstname, widget: string }
      - { label: "Last Name", name: lastname, widget: string }
      - { label: "Role", name: role, widget: string }
      - { label: "Email", name: email, widget: string, required: false }
      - { label: "Photo", name: photo, widget: image, required: false, hint: "Please use a square photo." }
      - { label: "Order of Appearance", name: ordering, widget: number, required: false, value_type: "int", default: 10, min: 0, max: 100, hint: "This should usually be left unchanged. By default, the website will list team members by last name." }
      - { label: "Description", name: body, widget: markdown, required: false }

  - label: Emerging Technology
    name: emerging-technology
    folder: _technologies
    create: true
    media_folder: "/assets/files/techradar"
    fields:
      - { label: "Title", name: title, widget: string }
      - { label: "Subtitle", name: subtitle, widget: string }
      - { label: "Excerpt", name: excerpt, widget: text }
      - { label: "Image", name: image, widget: image }
      - { label: "Content", name: body, widget: markdown }
      - label: "Resources"
        name: resources
        widget: list
        fields:
          - { label: "Title", name: title, widget: string }
          - { label: "URL", name: url, widget: string }
      - label: "Stakeholders"
        name: stakeholders
        widget: list
        fields:
          - { label: "Title", name: title, widget: string }
          - { label: "URL", name: url, widget: string }

  - label: Site Configuration
    name: configuration
    editor:
      preview: false
    files:
      - label: Navigation
        name: navigation
        file: _data/navigation.yml
        fields:
          - label: Primary Navigation Link
            name: primary
            widget: list
            fields:
              - { label: "Text", name: text, widget: string }
              - { label: "Link", name: href, widget: string }
