# Send a Slack notification when CMS content is ready for publication.

name: CMS notifier

on:
  pull_request_target:
    types: [labeled]

permissions:
  contents: read
  pull-requests: write

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack if a PR is ready to publish
        if: ${{ contains(github.event.pull_request.labels.*.name, 'netlify-cms/pending_publish') }}
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          payload: |
            {
              "message": "Content is ready for publication, please review and merge: ${{ github.event.pull_request.html_url }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_MESSAGE_URL }}
