name: Tests

on: [pull_request]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm

      - name: Install Node dependencies
        run: npm install

  general_tests:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm

      - name: Install Node dependencies
        run: npm install

      - name: Run JavaScript linter
        run: npm run test:eslint

      - name: Run internal link checker
        run: npm run test:links:internal

  accessibility_tests:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm

      - name: Install Node dependencies
        run: npm install

      - name: Run accessibility tests
        run: npm run test:a11y:local
